module.exports = {
    FETCHING_DATA_SUCCESS: "FETCHING_DATA_SUCCESS",
    DATABASE_ERROR: "DATABASE_ERROR",
    UPDATING_OBJECT_SUCCESS: "UPDATING_OBJECT_SUCCESS", 
    INVALID_PARAMS: "INVALID_PARAMS"
    
}